# SPDX-License-Identifier: MIT
#
# Copyright (c) 2020, Johannes Stoelp <dev@memzero.de>

name: check-examples
on: [push, pull_request]

jobs:
  check_examples:
    runs-on: ubuntu-latest
    name: Check examples (all ARCHs)
    steps:
    - name: Checkout project
      uses: actions/checkout@v2
    - name: Build docker image
      run: |
          docker/build.sh matcha-box
    - name: Run examples
      run: |
          for arch in x86_64 arm64 arm riscv64; do
              echo -e "\e[1;32m==> check ARCH=$arch\e0m"
              docker run                 \
                  --rm                   \
                  --volume $PWD:/develop \
                  matcha-box /bin/bash -c "make ARCH=$arch clean demo1"
          done
